services:

  surrealdb:
    image: surrealdb/surrealdb:v2.1.2
    restart: always
    user: root
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - root
      - --pass
      - root
      - rocksdb:/data/surreal_db
    ports:
      - 8000:8000
    volumes:
      - "./data:/surreal_db"
