[package]
name = "hdc_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = {version = "1.0.215", features = ["derive"]}
serde_derive = "1.0.215"
serde_json = "1.0.133"
surrealdb = "2.1.1"
uuid = {version = "1.11.0", features = ["v4"]}
